package io.mincong.dvf.model;

import java.time.LocalDate;
import java.util.Optional;

public class TestModels {

  public static final ImmutableTransaction TRANSACTION_1 =
      ImmutableTransaction.builder()
          .mutationId("2020-1")
          .mutationDate(LocalDate.of(2020, 1, 7))
          .dispositionNumber("000001")
          .mutationNature("Vente")
          .propertyValue(8000)
          .addressNumber("")
          .addressSuffix("")
          .addressRoadName("FORTUNAT")
          .addressRoadCode("B063")
          .postalCode("01250")
          .communeCode("01072")
          .communeName("Ceyzériat")
          .departmentCode("01")
          .oldCommuneCode("")
          .oldCommuneName("")
          .plotId("01072000AK0216")
          .oldPlotId("")
          .volumeNumber("")
          .numberLot1("")
          .surfaceSquareLot1(Optional.empty())
          .numberLot2("")
          .surfaceSquareLot2(Optional.empty())
          .numberLot3("")
          .surfaceSquareLot3(Optional.empty())
          .numberLot4("")
          .surfaceSquareLot4(Optional.empty())
          .numberLot5("")
          .surfaceSquareLot5(Optional.empty())
          .lotsCount(0)
          .localTypeCode("")
          .localType("")
          .realBuiltUpArea(Optional.empty())
          .principlePiecesCount(Optional.empty())
          .natureCultureCode("T")
          .natureCulture("terres")
          .specialNatureCultureCode("")
          .specialNatureCulture("")
          .landSurface(1061)
          .longitude(5.323522)
          .latitude(46.171899)
          .build();

  public static final ImmutableTransaction TRANSACTION_2 =
      ImmutableTransaction.builder()
          .mutationId("2020-2")
          .mutationDate(LocalDate.of(2020, 1, 7))
          .dispositionNumber("000001")
          .mutationNature("Vente")
          .propertyValue(75000)
          .addressNumber("")
          .addressSuffix("")
          .addressRoadName("RUE DE LA CHARTREUSE")
          .addressRoadCode("0064")
          .postalCode("01960")
          .communeCode("01289")
          .communeName("Péronnas")
          .departmentCode("01")
          .oldCommuneCode("")
          .oldCommuneName("")
          .plotId("01289000AI0210")
          .oldPlotId("")
          .volumeNumber("")
          .numberLot1("")
          .surfaceSquareLot1(Optional.empty())
          .numberLot2("")
          .surfaceSquareLot2(Optional.empty())
          .numberLot3("")
          .surfaceSquareLot3(Optional.empty())
          .numberLot4("")
          .surfaceSquareLot4(Optional.empty())
          .numberLot5("")
          .surfaceSquareLot5(Optional.empty())
          .lotsCount(0)
          .localTypeCode("")
          .localType("")
          .realBuiltUpArea(Optional.empty())
          .principlePiecesCount(Optional.empty())
          .natureCultureCode("AB")
          .natureCulture("terrains a bâtir")
          .specialNatureCultureCode("")
          .specialNatureCulture("")
          .landSurface(610)
          .longitude(5.226197)
          .latitude(46.184538)
          .build();

  public static final ImmutableTransaction TRANSACTION_3 =
      ImmutableTransaction.builder()
          .mutationId("2020-3")
          .mutationDate(LocalDate.of(2020, 1, 14))
          .dispositionNumber("000001")
          .mutationNature("Vente")
          .propertyValue(89000)
          .addressNumber("")
          .addressSuffix("")
          .addressRoadName("VACAGNOLE")
          .addressRoadCode("B112")
          .postalCode("01340")
          .communeCode("01024")
          .communeName("Attignat")
          .departmentCode("01")
          .oldCommuneCode("")
          .oldCommuneName("")
          .plotId("01024000AL0120")
          .oldPlotId("")
          .volumeNumber("")
          .numberLot1("")
          .surfaceSquareLot1(Optional.empty())
          .numberLot2("")
          .surfaceSquareLot2(Optional.empty())
          .numberLot3("")
          .surfaceSquareLot3(Optional.empty())
          .numberLot4("")
          .surfaceSquareLot4(Optional.empty())
          .numberLot5("")
          .surfaceSquareLot5(Optional.empty())
          .lotsCount(0)
          .localTypeCode("")
          .localType("")
          .realBuiltUpArea(Optional.empty())
          .principlePiecesCount(Optional.empty())
          .natureCultureCode("AB")
          .natureCulture("terrains a bâtir")
          .specialNatureCultureCode("")
          .specialNatureCulture("")
          .landSurface(600)
          .longitude(Optional.empty())
          .latitude(Optional.empty())
          .build();

  public static final ImmutableTransaction TRANSACTION_5 =
      ImmutableTransaction.builder()
          .mutationId("2020-4")
          .mutationDate(LocalDate.of(2020, 1, 22))
          .dispositionNumber("000001")
          .mutationNature("Vente")
          .propertyValue(209950)
          .addressNumber("11")
          .addressSuffix("")
          .addressRoadName("RUE REYER")
          .addressRoadCode("3340")
          .postalCode("01000")
          .communeCode("01053")
          .communeName("Bourg-en-Bresse")
          .departmentCode("01")
          .oldCommuneCode("")
          .oldCommuneName("")
          .plotId("01053000AL0074")
          .oldPlotId("")
          .volumeNumber("")
          .numberLot1("")
          .surfaceSquareLot1(Optional.empty())
          .numberLot2("")
          .surfaceSquareLot2(Optional.empty())
          .numberLot3("")
          .surfaceSquareLot3(Optional.empty())
          .numberLot4("")
          .surfaceSquareLot4(Optional.empty())
          .numberLot5("")
          .surfaceSquareLot5(Optional.empty())
          .lotsCount(0)
          .localTypeCode("1")
          .localType("Maison")
          .realBuiltUpArea(78)
          .principlePiecesCount(5)
          .natureCultureCode("S")
          .natureCulture("sols")
          .specialNatureCultureCode("")
          .specialNatureCulture("")
          .landSurface(242)
          .longitude(5.219902)
          .latitude(46.196484)
          .build();
}
